### ISSUE TITLE
Project Idea: Drone Operations Mobile App/Field Data Collection Solution

### ISSUE THREAD

**Issue by veragreen119** [lorrnel/I_Commander#2]
Commercial drone operators are required to follow numerous regulations.  Regulatory compliance tracking is a large component of drone operation and includes but is not limited to tracking of the following items:

- Drone hardware: drones and their associated status and service records such as maintenance records, hours flown, current issue, is the drone currently operational or in maintenance mode, reports regarding drone maintenance, etc.
-regulatory criteria - this is developed as a 1000 page word document with linkages and referencing embedded.  This document needs to be ported to a searchable, web accessible container such as Drupal. 
-pilot tracking: drone pilots mus meet numerous government regulations in terms of operator licensing.  A system (such as Drupal) is required to track plots against required regulations and provide an easy way to track compliance.  Pilots belong to a category and regulations belong to a category.  the pilot must maintain all of the operator certification required by his category.  Dates should also be tracked: date certified, valid until, etc. The system should have alerts which notify users when re-certification is upcoming.
-field forms: numerous field forms and checklists are required
-field SOP access: operators need to be able to access SOP's quickly and easily while in the field
-SOP Compliance: field operators must be able to fill out SOP checklists while in the field to fulfil regulatory requirements.
-Oversight: The flight operations manager needs to be able to see if SOP's have been completed.
-information filled out in the field must sync back to the core system (Drupal) when the operator is in wifi range if it can not be sent over cell data network.
-mobile app solution: Currently, a mobile app to manage field operations which meets the required functionality is NOT available. The existing solutions are limited to small operations such as a single operator and do not meet the requirements of a larger scale drone survey operation. The mobile app solution must integrate with a larger back-end system (Drupal)

The regulations, SOP's and form layout is known and can be provided. The idea is to build a prototype consisting of the TYPES of items required and an interface which allows users to add more items into existing type containers. 

The Lorrnel development environment and back-end database support is available to this project by Lorrnel.  Lorrnel staff are available to work with students to provide detailed requirements, sample data/content and to test the product.

**Lorrnel must retain the IP on the project results.** 
Students may use the project in their portfolio.

**Comment by veragreen119** [comment]
Kier, can you convert the attached into the README? Or a REQUIREMENTS Document. A few sketches to come. 
[I Commander.docx](https://github.com/lorrnel/SFU_CMPT276_2019/files/3715090/I.Commander.docx)

**Comment by syonfox** [comment]
@veragreen119  I dont have write access to the repository

**Comment by veragreen119** [comment]
I fixed your access.

**Comment by veragreen119** [comment]
No longer relavent
